### PR TITLE
provide an option to hide a line

### PR DESCRIPTION
**Pull request by Seasawher**
I love lean2md and would like to combine it with mdbook to write a book.

I seriously want the ability to hide certain lines.

This PR adds the ability to not output lines with `--:≡` at the end of the line to markdown.

`--:≡` is a symbol in the shape of a broom. This is rarely used at the end of a line, so adding this feature should not be a problem.

What would you think? Thank you for reading.

### CODE REVIEW

**Comment by arthurpaulino** [comment]
I'd rather some simpler rule, like "hide lines that start with `%`.

Also, this kind of change needs to be documented on the README. Can you add that too, please?

**Comment by Seasawher** [comment]
Thanks for your reply. So what about hiding lines ending in `--#`? This is another combination that rarely appears.

**Comment by arthurpaulino** [comment]
That's better. I see the appeal of marking hidden lines at the end: it doesn't mess up alignments.

**Comment by Seasawher** [comment]
done!

**Comment by arthurpaulino** [comment]
Thanks!!

**Pull request merged**
